-- CreateTable
CREATE TABLE "UserSessions" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "opened" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" INTEGER,
    CONSTRAINT "UserSessions_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
