name: Cypress tests
on: [push, pull_request, release, workflow_dispatch]
jobs:
    cypress_tests:
        name: Run cypress tests
        runs-on: ubuntu-latest

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v3

            - name: Build docker image
              run: docker build . -t sinv

            - name: Start docker container
              run: docker run -p 80:80 -v "$(pwd)"/data:/data -d sinv

            - name: Install dependencies
              run: |
                  npm i --include=dev
                  cd backend
                  npm i --include=dev
                  npx prisma generate
                  cd ..

            - name: Give permissions for sinv.db
              run: sudo chmod +rwx data/sinv.db

            - name: Run cypress tests
              run: npx cypress run
