name: Cypress tests
on: [push, pull_request, release, workflow_dispatch]
jobs:
  start_server:
    name: Build everything and start the backend
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Build docker image
        run: docker build . -t sinv
      
      - name: Start docker container
        run: docker run -p 80:80 -d sinv
        
  cypress_tests:
    name: Run the cypress tests
    runs-on: ubuntu-latest
    needs: start_server
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm i --include=dev
        
      - name: Run cypress tests
        run: npx cypress run
